---
title: "Object Models"
author: "Kenneth Brevoort"
date: "September 13, 2015"
output: html_document
---

This page will describe the objects created by the tabler package.  

# colRec:  Column Objects

colRec objects are S3 objects that serve as intermediate steps in the creation
of the tabler object.  colRecs are created from estimation results.  They are
designed to be (relatively) easy to create.  This allows users to create results
formatted in a manner that can be incorporated into tabler, even if the
estimation method used to generate the results does not have an existing method.

| Attribute | Type | Description |
| :-------- | :--: | :---------- |
| depVar | Scalar | Name of the dependent variable |
| estType | Scalar | Name of the estimation method used |
| varNames | Vector | Names of right hand side variables |
| xlevels | List | Levels associated with each factor variable.  Each element has name of factor variable and contains a vector of levels |
| coefs | data.frame | Output coefficient information:  Coefficient, Standard Error, t-statistic, and p-value |
| gof | data.frame | Goodness of fit statistics.  Each variable is a statistic. |

# tablerObject

tablerObjects are S3 objects that hold the combined information of the table.

| Attribute | Type | Description |
| :-------- | :--: | :---------- |
| title | Character | Title of the table (optional) |
| notes | Character | Notes to be included at the bottom (or top) of the table |
| number | Scalar | Number of the table (optional) to be displayed with title |
| depVars | Vector | Dependent variables used in each estimation |
| estTypes | Vector | Types of estimations conducted |
| varNames | Vector | Variable names used across the estimations |
| xlevels | List | List of levels associated with each factor variable |
| coefs | data.frame | Stacked data frame that contains all of the coefficient tables |
| gofs | data.frame | Stacked data frame that contains all of the goodness of fit statistics |
| theme | tablerTheme | Tabler theme description |

-------------------------------------------------------------
 Centered   Default           Right Left
  Header    Aligned         Aligned Aligned
----------- ------- --------------- -------------------------
   First    row                12.0 Example of a row that
                                    spans multiple lines.

  Second    row                 5.0 Here's another one. Note
                                    the blank line between
                                    rows.
-------------------------------------------------------------
